// Maps each source wiki's relative .md path → absolute VitePress route.
// `null` means the source file is discarded in the migration.
// Relative anchor links preserved by the migration script.

export const BANDARAYA = {
  "README.md":                  null,
  "welcome.md":                 "/bandaraya/get-started",
  "getting-started.md":         "/bandaraya/get-started",
  "teams.md":                   "/bandaraya/teams",
  "jobs.md":                    "/bandaraya/jobs",
  "economy.md":                 "/bandaraya/economy",
  "vehicles.md":                "/bandaraya/vehicles",
  "getting-around.md":          "/bandaraya/getting-around",
  "emergency-services.md":      "/bandaraya/emergency-services",
  "combat-and-health.md":       "/bandaraya/combat-and-health",
  "arrest-and-law.md":          "/bandaraya/arrest-and-law",
  "phone.md":                   "/bandaraya/phone",
  "tablet.md":                  "/bandaraya/tablet",
  "gamepasses.md":              "/bandaraya/gamepasses",
  "map.md":                     "/bandaraya/locations",
  "rules.md":                   "/bandaraya/rules",
  "glossary.md":                "/bandaraya/glossary",
  "faq.md":                     "/bandaraya/faq",
};

export const LEBUHRAYA = {
  "README.md":                  null,
  "getting-started.md":         "/lebuhraya/get-started",
  "controls.md":                "/lebuhraya/controls",
  "teams-and-careers.md":       "/lebuhraya/teams",
  "jobs.md":                    "/lebuhraya/jobs",
  "economy-and-xp.md":          "/lebuhraya/economy",
  "vehicles.md":                "/lebuhraya/vehicles",
  "shops.md":                   "/lebuhraya/shops",
  "world-and-map.md":           "/lebuhraya/map",
  "housing.md":                 "/lebuhraya/housing",
  "social-features.md":         "/lebuhraya/social-features",
  "passes-and-boosts.md":       "/lebuhraya/passes-and-boosts",
  "faq.md":                     "/lebuhraya/faq",
};

export const SUMAYA = {
  "README.md":                      null,
  "getting-started.md":             "/sumaya/get-started",
  "teams.md":                       "/sumaya/teams",
  "phone-and-ui.md":                "/sumaya/phone",
  "economy.md":                     "/sumaya/economy",
  "progression.md":                 "/sumaya/progression",
  "careers/overview.md":            "/sumaya/jobs",
  "careers/fishing.md":             "/sumaya/jobs-fishing",
  "careers/service-sector.md":      "/sumaya/jobs-service",
  "careers/palm-oil.md":            "/sumaya/jobs-palm-oil",
  "emergency-services/overview.md": "/sumaya/emergency-services",
  "emergency-services/polis.md":    "/sumaya/polis",
  "emergency-services/bomba.md":    "/sumaya/bomba",
  "emergency-services/kesihatan.md":"/sumaya/kesihatan",
  "vehicles.md":                    "/sumaya/vehicles",
  "housing.md":                     "/sumaya/housing",
  "crime-and-law.md":               "/sumaya/crime-and-law",
  "quests.md":                      "/sumaya/quests",
  "tips-and-tricks.md":             "/sumaya/tips-and-tricks",
  "glossary.md":                    "/sumaya/glossary",
};

// Descriptions are seeded from a handwritten table (1-2 sentences for SEO).
// The migration script uses these to populate frontmatter `description`.
// If a slug is missing here, the script falls back to the first paragraph.

export const DESCRIPTIONS = {
  "/bandaraya/get-started":        "Start your adventure in Bandaraya — navigate menus, earn Bandaraya Ringgit (BR), pick a team, and explore Kuala Lumpur.",
  "/bandaraya/teams":              "Complete guide to every team in Bandaraya — emergency services, military, transport, civilian, government, and more.",
  "/bandaraya/jobs":               "Every job in Bandaraya — postal service, taxi driving, towing, bus driving, and agency jobs — with pay rates and ranks.",
  "/bandaraya/economy":            "How the Bandaraya Ringgit (BR) economy works — earning, banking, transferring BR, and developer products.",
  "/bandaraya/vehicles":           "Spawning, driving, fuel, and buying or renting vehicles in Bandaraya.",
  "/bandaraya/getting-around":     "Public transport in Bandaraya — MRT, LRT, monorail, buses, CAG card, e-hailing, and TapNGo tolls.",
  "/bandaraya/emergency-services": "PDRM, BOMBA, KKM, SJAM, RELA, MAF, and KPTD — the emergency and security services of Bandaraya.",
  "/bandaraya/combat-and-health":  "Weapons, armor, injuries, and the medical system in Bandaraya.",
  "/bandaraya/arrest-and-law":     "How arrests work in Bandaraya — LTAA, RTAA, summons, jail time, and suspect rights.",
  "/bandaraya/phone":              "The in-game phone in Bandaraya — MyPay, e-hailing, 999, MyCar, MyTow, messages, and more apps.",
  "/bandaraya/tablet":             "The team-gated tablet tool in Bandaraya — MDT, MyEmergency, MyTow, KKM Logger, and other apps.",
  "/bandaraya/gamepasses":         "Every Bandaraya gamepass explained — Taxi Driver, Firearms Licence, HCC, Car Radio, and more.",
  "/bandaraya/locations":          "Landmarks, buildings, streets, stations, hospitals, and shops across Bandaraya.",
  "/bandaraya/shops":              "Shops in Bandaraya — food, weapons, snacks, utilities, and where to find them.",
  "/bandaraya/rules":              "What behaviour gets you banned in Bandaraya, and how appeals work.",
  "/bandaraya/glossary":           "Malaysian acronyms and in-game terms explained — PDRM, BOMBA, KKM, CAG, LTAA, RTAA, MRT, and more.",
  "/bandaraya/faq":                "Common new-player questions in Bandaraya.",

  "/lebuhraya/get-started":        "Your first 10 minutes in Lebuhraya — spawn a vehicle, earn BR, level up, and hit the highway.",
  "/lebuhraya/controls":           "Every control in Lebuhraya — keyboard, gamepad, mobile, and VR inputs.",
  "/lebuhraya/teams":              "All 18 teams in Lebuhraya and the 20-tier rank system.",
  "/lebuhraya/jobs":               "Every job in Lebuhraya — grouped by agency (Pengangkutan and more) with pay rates.",
  "/lebuhraya/economy":            "Ringgit (BR), levels 1-500, XP multipliers, and the fastest ways to earn in Lebuhraya.",
  "/lebuhraya/vehicles":           "All 127 vehicle models in Lebuhraya — spawning, fuel, crashing, and customization.",
  "/lebuhraya/shops":              "Food, snack, and utility shops across Lebuhraya.",
  "/lebuhraya/map":                "Bandar Seri Putra, Jersik, Kampung Merbang, and 29 key locations across Lebuhraya.",
  "/lebuhraya/housing":            "Claim a plot and build your home in Lebuhraya.",
  "/lebuhraya/social-features":    "Convoy, 999 Emergency, and the in-game phone in Lebuhraya.",
  "/lebuhraya/passes-and-boosts":  "Gamepasses, XP boosts, and Premium benefits in Lebuhraya.",
  "/lebuhraya/faq":                "Common questions and quick wins for new Lebuhraya players.",

  "/sumaya/get-started":           "Start playing Sumaya — main menu, team pick, controls, and the first five minutes in town.",
  "/sumaya/teams":                 "The five teams of Sumaya — Visitors, Malaysians, POLIS, BOMBA, and Kesihatan.",
  "/sumaya/phone":                 "The 12 phone apps, HUD, and minimap in Sumaya.",
  "/sumaya/economy":               "Ringgit (SR), wallet vs bank mechanics, and earning in Sumaya.",
  "/sumaya/progression":           "XP, levels, ranks, and the fastest paths to climb in Sumaya.",
  "/sumaya/jobs":                  "The three civilian career sectors in Sumaya — fishing, service, and palm oil.",
  "/sumaya/jobs-fishing":          "Fishing in Sumaya — spots, fish types, prices, and progression.",
  "/sumaya/jobs-service":          "Mamak and fast-food service careers in Sumaya.",
  "/sumaya/jobs-palm-oil":         "Palm oil and agriculture work in Sumaya.",
  "/sumaya/emergency-services":    "POLIS, BOMBA, and Kesihatan — the emergency services of Sumaya.",
  "/sumaya/polis":                 "Playing POLIS in Sumaya — patrols, arrests, ranks, and equipment.",
  "/sumaya/bomba":                 "Playing BOMBA (fire brigade) in Sumaya — tenders, hydrants, and fires.",
  "/sumaya/kesihatan":             "Playing Kesihatan (medical) in Sumaya — ambulances, treatment, and revival.",
  "/sumaya/vehicles":              "Cars, boats, ambulances, spawners, and customization in Sumaya.",
  "/sumaya/housing":               "Plots, templates, tiers, furniture, and selling homes in Sumaya.",
  "/sumaya/crime-and-law":         "Carjacking, pickpocketing, wanted stars, and jail in Sumaya.",
  "/sumaya/quests":                "The 12-step discovery quest chain in Sumaya.",
  "/sumaya/tips-and-tricks":       "Hidden interactions, mobile quirks, and expert tips for Sumaya.",
  "/sumaya/glossary":              "Malay words and in-game terms explained for Sumaya players.",
};
